[build]
  command = "echo \"export const environment = { production: true, supabaseUrl: '$SUPABASE_URL', supabaseKey: '$SUPABASE_KEY' };\" > src/app/environments/environment/environment.ts && npm install --legacy-peer-deps && npx ng build"
  publish = "dist/recipe-app"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = "src/app/environments"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
